name: junction
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.9+58

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # ---- Core Firebase ----
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  firebase_messaging: ^15.2.10
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.2

  # ---- Notifications ----
  flutter_local_notifications: ^17.2.3

  # ---- Other dependencies ----
  http: ^1.5.0
  cupertino_icons: ^1.0.8
  intl: ^0.18.0
  shared_preferences: ^2.2.2
  image_picker: ^1.1.0
  path: ^1.9.0
  share_plus: ^10.0.0
  google_maps_flutter: ^2.5.0
  geolocator: ^11.0.0
  geocoding: ^2.1.0
  permission_handler: ^11.3.0
  carousel_slider: ^4.2.0
  flutter_svg: ^2.0.7
  flutter_image_compress: ^2.1.0
  path_provider: ^2.1.1
  async: ^2.8.2
  connectivity_plus: ^5.0.2
  razorpay_flutter: ^1.3.5
  lucide_icons: ^0.257.0
  url_launcher: ^6.2.5
  app_links: ^6.3.1
  webview_flutter: ^4.4.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
